version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "80:8080"  # Map directly to port 80
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - ./frontend:/app/static
    restart: unless-stopped

# Remove the frontend service entirely

networks:
  app-network:
    driver: bridge
