version: "3.9"

services:
  backend:
    build: 
     context: .
     dockerfile: ./backend/Dockerfile
    container_name: backend-app
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - ./backend:/app
      - ./frontend:/app/static  # Serve frontend static files from backend
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    driver: bridge
